config/routes.rb
Rails.application.routes.draw do

  devise_for :lifters
  root 'one_rep_maxes#index'
  
  resources :lifters, only: [:index] do
    get '/new_week' => 'one_rep_maxes#new_week'
    resources :one_rep_maxes, only: [:new, :create, :index] do
      get '/plan' => 'workouts#show' 
    end
  end

end

app/models/lift_calculator.rb
class LiftCalculator
  
  def initialize(one_rep_maxes)
    @one_rep_maxes = one_rep_maxes
  end
  
  #Takes in 1 rep max, the week (1-4), lift type and percentage
  def calculate_weight(day, percentage)
    if day == 1 #overheadpress
      @one_rep_maxes.overheadpress*percentage
    elsif day == 2 #deadlift
      @one_rep_maxes.deadlift*percentage
    elsif day == 3 #benchpress
      @one_rep_maxes.benchpress*percentage
    elsif day == 4 #squats
      @one_rep_maxes.squat*percentage
    end
  end
  
  def lift_percentages(week)
    if week == 1
      [0.4, 0.5, 0.6, 0.65, 0.75, 0.85]
    elsif week == 2
      [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    elsif week == 3
      [0.4, 0.5, 0.6, 0.75, 0.85, 0.95]
    elsif week == 4
      [0.4, 0.5, 0.6, 0.40, 0.50, 0.60]
    end
  end
  
  def lift_reps(week)
    if week == 1
      [5, 5, 3, 5, 5, 5]
    elsif week == 2
      [5, 5, 3, 3, 3, 3]
    elsif week == 3
      [5, 5, 3, 5, 3, 1]
    elsif week == 4
      [5, 5, 3, 5, 5, 5]
    end
  end
  
  def lift_table

    table = []
    (1..4).each do |week|
      week_table = []
      (1..4).each do |day|
        day_column = []
        column_values = lift_percentages(week).zip lift_reps(week)
        column_values.each do |percent, reps|
          day_column.push("#{nearest_5(calculate_weight(day, percent).to_i)} x #{reps}")
        end
        week_table.push(day_column)
      end
    table.push(week_table)
    end
    return table
  end
  
  def nearest_5 weight
    
    remainder = weight % 5
    
    if remainder >= 3 
      weight + 5 - remainder
    else
      weight - remainder
    end
  end
  
end

app/models/lifter.rb
class Lifter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :one_rep_maxes, :dependent => :destroy
end

app/models/one_rep_max.rb
class OneRepMax < ActiveRecord::Base
  belongs_to :lifter
  
  attr_accessor :deadlift_reps, :squat_reps, :benchpress_reps, :overheadpress_reps
  attr_accessor :deadlift_wt, :squat_wt, :benchpress_wt, :overheadpress_wt
  
  before_validation :calculate_one_rep_max
  validates_presence_of :deadlift, :squat, :benchpress, :overheadpress

  
  private
    def calculate_one_rep_max
      if deadlift_reps.to_i != 1
        self.deadlift = deadlift_wt.to_i * deadlift_reps.to_i * 0.0333 + deadlift_wt.to_i
      else
        self.deadlift = deadlift_wt.to_i
      end
      
      if squat_reps.to_i != 1
        self.squat = squat_wt.to_i * squat_reps.to_i * 0.0333 + squat_wt.to_i
      else
        self.squat = squat_wt.to_i
      end
      
      if benchpress_reps.to_i != 1
        self.benchpress = benchpress_wt.to_i * benchpress_reps.to_i * 0.0333 + benchpress_wt.to_i
      else
        self.benchpress = benchpress_wt.to_i
      end
      
      if overheadpress_reps.to_i != 1
        self.overheadpress = overheadpress_wt.to_i * overheadpress_reps.to_i * 0.0333 + overheadpress_wt.to_i
      else
        self.overheadpress = overheadpress_wt.to_i
      end
      
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_lifter!
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :current_password) }
    end
end

app/controllers/lifters_controller.rb
class LiftersController < ApplicationController
  
  def index
    @lifters = Lifter.all
  end
end

app/controllers/one_rep_maxes_controller.rb
class OneRepMaxesController < ApplicationController
  
  def show
  end
  
  def index
    @lifter = find_lifter
    @maxes = @lifter.one_rep_maxes.order('created_at DESC')
  end
  
  def new
    @lifter = find_lifter
    @previous_max = @lifter.one_rep_maxes.last
    @max = @lifter.one_rep_maxes.new
  end
  
  def new_week
    @lifter = find_lifter
    @new_max = increment_maxes @lifter.one_rep_maxes.last
    @max = @lifter.one_rep_maxes.new
  end
  
  def create
    #modify this code to later either update the previous entry from that day
    #or create the entry if its the first on that day
    #this will require allowing the user to select the date they got the lift at
    #first_or_create!
    #@entry = Entry.where(created_at: Time.now.beginning_of_day.utc..Time.now.end_of_day.utc).first_or_create!
    #@entry.update_attributes(entry_params)
    @lifter = find_lifter
    @max = @lifter.one_rep_maxes.new(one_rep_max_params)
    @max.save
    redirect_to lifter_one_rep_maxes_path(@lifter)
  end
  
  def update
  end
  
  def destroy
  end
  
  private
    
    def one_rep_max_params
      params.require(:one_rep_max).permit(:deadlift_wt, :squat_wt, :benchpress_wt, :overheadpress_wt,
                                          :deadlift_reps, :squat_reps, :benchpress_reps, :overheadpress_reps)
    end

  
    def find_lifter
      Lifter.find(current_lifter.id)
    end
 
    def increment_maxes maxes
      maxes.deadlift += 10
      maxes.squat += 10
      maxes.benchpress += 5
      maxes.overheadpress += 5
      return maxes
    end
      
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  protect_from_forgery with: :exception
  
  def show
    @maxes = OneRepMax.find(params[:one_rep_max_id])
    @table = LiftCalculator.new(@maxes).lift_table
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lifters_helper.rb
module LiftersHelper
end

app/helpers/one_rep_maxes_helper.rb
module OneRepMaxesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
</head>
<body>
  
  <header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "liftO", root_path , id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
        <% if lifter_signed_in? %>
            <li><%= link_to "Account: " + current_lifter.name, edit_lifter_registration_path  %></li>
            <li><%= link_to "Logout", destroy_lifter_session_path, method: :delete  %></li>
        <% else %>
            <li><%= link_to "Sign up", new_lifter_registration_path %></li>
            <li><%= link_to "Login", new_lifter_session_path  %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </div>

  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/lifters/index.html.erb
<table>
<% @lifters.each do |lifter| %>
      <tr>
        <td><%= lifter.name %></td>
        <td><%= lifter.email %></td>
        <td><%= link_to "Lifts", lifter_one_rep_maxes_path(lifter) %></td>
      </tr>
<% end %>
</table>

app/views/one_rep_maxes/index.html.erb
<%= link_to "Enter New Maxes", new_lifter_one_rep_max_path(@lifter) %> - 
<%= link_to "Increment Previous Week's Maxes", lifter_new_week_path(@lifter) %>
<br>
<div>
  <table class="table table-striped table-hover">
    <tr>
      <th>Date</th>
      <th>Deadlift</th>
      <th>Squat</th>
      <th>Bench Press</th>
      <th>Overhead Press</th>
      <th></th>
    </tr>
    <% @maxes.each do |max| %>
    <tr>
      <td><%= max.created_at.strftime("%d-%m-%Y") %></td>
      <td width="14%"><%= max.deadlift %></td>
      <td width="12%"><%= max.squat %></td>
      <td width="16%"><%= max.benchpress %></td>
      <td width="18%"><%= max.overheadpress %></td>
      <td><%= link_to "Generate Workout Plan", lifter_one_rep_max_plan_path(@lifter, max) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/one_rep_maxes/new.html.erb
<div>
<%= link_to "<< Back", lifter_one_rep_maxes_path %>
</div>
<%= form_for [@lifter, @max] do |f| %>
  <table class="table">
    <tr>
      <th></th>
      <th>Weight</th>
      <th>Reps</th>
    </tr>
    <tr>
      <td>
        <%= f.label :deadlift %>
      </td>
      <td>
        <%= f.number_field :deadlift_wt, :value=>(@previous_max.try(:deadlift))  %>
      </td>
      <td>
        <%= f.number_field :deadlift_reps, :value=>(1)  %>
      </td>
    </tr>
    
    <tr>
      <td>
        <%= f.label :squat %>
      </td>
      <td>
        <%= f.number_field :squat_wt, :value=>(@previous_max.try(:squat)) %>
      </td>
      <td>
        <%= f.number_field :squat_reps, :value=>(1) %>
      </td>
    </tr>
      
    <tr>
      <td>
        <%= f.label :benchpress %>
      </td>
      <td>
        <%= f.number_field :benchpress_wt, :value=>(@previous_max.try(:benchpress)) %>
      </td>
      <td>
        <%= f.number_field :benchpress_reps, :value=>(1) %>
      </td>
      
    </tr>
    
    <tr>
      <td>
        <%= f.label :overheadpress, "Overhead Press" %>
      </td>
      <td>
        <%= f.number_field :overheadpress_wt, :value=>(@previous_max.try(:overheadpress)) %>
      </td>
      <td>
        <%= f.number_field :overheadpress_reps, :value=>(1) %>
      </td>
      
    </tr>
    
  </table>
  <br>
  <div class="text-center"> 
    <%= f.submit "Create One Rep Max", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/one_rep_maxes/new_week.html.erb
<div>
<%= link_to "<< Back", lifter_one_rep_maxes_path %>
</div>
<%= form_for [@lifter, @max] do |f| %>
  <table>
    <tr>
      <td>
        <%= f.label :deadlift %>
      </td>
      <td>
        <%= f.number_field :deadlift_wt, :value=>(@new_max.deadlift)  %>
      </td>
      <td>
        <%= f.number_field :deadlift_reps, :value=>(1)  %>
      </td>
    </tr>
    
    <tr>
      <td>
        <%= f.label :squat %>
      </td>
      <td>
        <%= f.number_field :squat_wt, :value=>(@new_max.squat) %>
      </td>
      <td>
        <%= f.number_field :squat_reps, :value=>(1) %>
      </td>
    </tr>
      
    <tr>
      <td>
        <%= f.label :benchpress %>
      </td>
      <td>
        <%= f.number_field :benchpress_wt, :value=>(@new_max.benchpress) %>
      </td>
      <td>
        <%= f.number_field :benchpress_reps, :value=>(1) %>
      </td>
      
    </tr>
    
    <tr>
      <td>
        <%= f.label :overheadpress, "Overhead Press" %>
      </td>
      <td>
        <%= f.number_field :overheadpress_wt, :value=>(@new_max.overheadpress) %>
      </td>
      <td>
        <%= f.number_field :overheadpress_reps, :value=>(1) %>
      </td>
      
    </tr>
    
  </table>
  <br>
  <div>
    <%= f.submit "Create One Rep Max" %>
  </div>
<% end %>

app/views/workouts/show.html.erb
<div>
<%= link_to "<< Back", lifter_one_rep_maxes_path %>
</div>

<% @table.each_with_index do |week, index| %>
  
  <h1 align="center">Week <%= index + 1 %></h1>
  <table class="table table-striped table-hover" align="center">
    <tr>
      <th></th>
      <th>Day 1 - Overhead Press</th>
      <th>Day 2 - Deadlift</th>
      <th>Day 3 - Benchpress</th>
      <th>Day 4 - Squats</th>
    </tr>

  <% j = week[0].length - 1 %>
  <% i = week.length - 1 %>

  <% for j in (0..j) do %>
    <tr>
      <% if j == 0 %>
        <td rowspan=3>Warm-Up</td>
      <% elsif j == 3 %>
        <td rowspan=3>5/3/1</td>
      <% end %>
      <% for i in (0..i) do %>
        <td><%= week[i][j] %>
      <% end %>
    </tr>
  <% end %>
  </table>

<% end %>